### ISSUE TITLE
dgl package not found

### ISSUE THREAD

**Issue by shangyuan191** [JhuoW/PMP_submit#1]
![image](https://github.com/Xtra-Computing/PMP/assets/162014532/b278dbd5-1d6a-4691-9d8d-274f6472046b)

**Comment by Omahqwen** [comment]
i have also encountered this problem. please is there anyway to solve this issue?

**Comment by JhuoW** [comment]
This issue may be caused by a bug during the generation of the requirements.txt file. Please directly install any version of DGL that matches the CUDA version on your server.

**Comment by Omahqwen** [comment]
thanks, it works now
